statsd/statsd

.pkgr.yml
packager/Procfile
packager/postinst

This pull request enables automatic packaging of statsd for Debian/Ubuntu/CentOS/RHEL using packager.io. The packages come with init scripts and a facility to install additional npm modules if needed.
Example installation instructions at https://packager.io/gh/pkgr/statsd/install?bid=15#ubuntu-14-04-statsd

Enable packaging at https://packager.io/gh/pkgr/statsd

---

backends/console.js

Pretty was using an invalid invocation of util.inspect(). Perhaps it was
valid pre-v0.10, but inspect now takes an options object.

Fix prettyprint option for console backend

---

lib/helpers.js
test/helpers_tests.js

Lines with negative sampling make server crash.
```
metric_name:43|ms|@-1.000000
```
will cause crash at `stats.js:240`:
```
sampleRate = Number(fields[2].match(/^@([\d\.]+)/)[1]);
```
because there is no match for `([\d\.]+)` group. Solution is to add additional validation against negative numbers in `helpers.js`.

Validate negative sampling

---

docs/metric_types.md

Code does accept a sample rate for time metrics:
https://github.com/etsy/statsd/blob/bad366cd438cd59b2064dd03ff3d415fc7db0c4b/stats.js#L206-L225
At least one client sends these (Openstack Swift) and at least one
server implementation considers them malformed currently (collectd),
presumbaly due to the bad docs :)
Fixes #435

Describe timer sample rate in metric_types docs. Fixes #435

---

backends/graphite.js
exampleConfig.js
stats.js
test/graphite_tests.js

Taking a stab at moving the metric name sanitization to the backend, as described originally in #110 (also refs #154).
This moves the Graphite-specific stat name regular expressions to the Graphite backend. Other backends should implement similar stat name expression cleanups based on their permitted character codes.
One issue that is not handled: Since the original code was performing these name changes at the time of ingress, it was possible that two stat reports could map to the same name. For example, the following two packets would map to the same timing metric:
```
glork:320|ms
gl+ork:320|ms
```
With this patch, these metrics will be tracked separately, but will both be submitted to Graphite using the same name "glork". Therefore, the second metric will likely overwrite the first …

Move stat key name sanitization to Graphite backend.

---

package.json

Just updating the node-syslog version in dependencies now that you can install 1.2.0 and run statsd without having it crash!

Pin to new node-syslog release that fixes #510

---

backends/graphite.js
lib/set.js
test/set_tests.js

two minor tweaks to set.js...
1. the first is to have the sets only store a boolean to indicate that a key is stored rather than duplicating the key into the value.
2. the second adds the size method, which simply returns the size of the set. It seems that we only care about values for getting the actual size, so it makes sense to me to do this on the set itself.

Set nitpick

---

examples/ruby_example.rb
examples/ruby_example2.rb

Not closing the sockets explicitely causes them to hang around longer than expected, and can cause issues when the number of open sockets exceeds system limits.

Explicitly close UDP sockets in Ruby examples

---

backends/repeater.js
exampleConfig.js
package.json
servers/tcp.js
servers/udp.js
test/repeater_tests.js

This adds test coverage for the (existing) udp repeater, and adds a tcp version. 
The only config change is that `repeaterProtocol` can now be `"tcp"`.

implements a tcp repeater, with tests

---

exampleConfig.js
stats.js

Example config looks something like this:
```
{
servers: [
{server: './servers/tcp', address: '0.0.0.0', port: 6125}
, {server: './servers/udp', port: 6125}
]
}
```
In the absence of a servers key, we look at the same variables under the top-level config, which is backwards compatible with the current behavior.

Support loading multiple servers.

---

debian/control

npm is used in debian/postinst script.

Add npm to deb package dependencies

---

docs/backend.md

Add a link to the StatsD backend for [Jut](http://www.jut.io).

add statsd-jut-backend

---

debian/postinst

The `devDependencies` don't seem to be necessary in production. Food for thought?

Fix: only install production dependencies

---

.travis.yml
lib/logger.js
package.json

node-syslog doesn't work with newer node.js versions and it's website says it not supported, so changed this dependency to modern-syslog library.
https://github.com/schamane/node-syslog
nodeunit 0.7.x doesn't compatible with newer node.js versions, so an update was required.
https://github.com/caolan/nodeunit/issues/291

Make statsd work with newer version of node

---

stats.js

As you known, without 'var', the variable 'subconfig' is global variable .
But I find that the 'subconfig'  only used between 330 and 335 in statsd.js 
```javascript
330               subconfig = config[prop];
331               for (var subprop in subconfig) {
332                 if (!subconfig.hasOwnProperty(subprop)) {
333                   continue;
334                 }
335                 stream.write(prop + " > " + subprop + ": " + subconfig[subprop] + "\n");
336               }
```
I mind that You don't want subconfig to pollute global.

change subconfig(at statsd.js 330:15) to local variable

---

debian/changelog

Otherwise we get a perl date parsing error while trying to do dpkg-buildpackage

Fix date in debian changelog

---

backends/graphite.js
docs/graphite_pickle.md
exampleConfig.js
test/graphite_pickle_tests.js
test/graphite_tests.js

Add support for the graphite pickle wire protocol.
There are two new configuration options related to graphite:
{ graphitePicklePort: 2004,
graphiteProtocol: "pickle" }
If `graphiteProtocol` is configured as pickle then the `graphitePicklePort` is used instead of the current `graphitePort` configuration. Both `graphitePicklePort` and `graphitePort` now default to their well-known values, making them optional.
The limited implementation of the Python pickle format required for Graphite support is documented in `graphite_pickle.md`.
The tests in `graphite_pickle_tests.js` invoke a Python script to verify that the packets received over the wire are able to be interpreted. This means that a Python interpreter is expected to be in the path.
Replaces #312.

support pickle to graphite

---

exampleConfig.js
servers/tcp.js
test/server_tests.js

* Add socket config option to specify path where socket will be stored.
* Add socket_mod config option to set correct permission on socket file.
* Remove socket on process exit.
* Update exampleConfig.js.

Allow to use unix domain sockets.

---

stats.js

See https://github.com/etsy/statsd/issues/574 for a full exploration and explanation of this PR.

Account for negative clock skew in flushMetrics

---

docs/backend.md

http://graphite.wikidot.com/ says it is out of date on the left hand side and links to the read the docs

Updated graphite link to read the docs

---

docs/backend.md

Add a link in backend documentation to the official statsd plugin for the platform Warp10.

Add plugin Warp10 backend

---

.travis.yml
package.json

If we're reiving the project, we should probably begin by moving to support in line with the nodejs LTS versions just to begin with. I'm not proposing we move with it (although it wouldn't be a bad idea) but doing this should help us bring the latest performance update and node features into the project and begin moving it forward.

begin testing on node lts and up

---

utils/check_statsd_health

This commit removes the -q switch which isn't supported by all netcat
variants. More information in #602.

removes -q switch

---

docs/backend.md

Added to [`docs/backend.md`](https://github.com/statsd/statsd/blob/master/docs/backend.md) (!) list *not* the Wiki [`Backends`](https://github.com/statsd/statsd/wiki/Backends) per #656 
*NB* The repo's `README.md` references a different page (with a different list of) [`docs/backend.md`](https://github.com/statsd/statsd/blob/master/docs/backend.md) than the Wiki [`Backends`](https://github.com/statsd/statsd/wiki/Backends). The docs page appears (!) more current and accurate.
Recommend dropping the Wiki page.

Add "opencensus-backend"

---

docs/backend.md

We have a duplicated list of backends across the main repo docs and the wiki docs, since the one in the main repo be edited via pull requests a bit easier I've added the one it was missing. If this gets merged, I suggest we remove the page from the wiki.
It might make sense to port the entire wiki into the `/docs` dir of the repo after this as well, thoughts?

add mysql backend link to docs/backend.md

---

MAINTAINERS.md

This is my submission to become an official statsd maintainer.
I'm a software engineer currently at Just-Eat, I live in the UK and have worked with nodejs for around 4-ish years. I've worked with node 0.10 all the way to node 10.x and have experience with TypeScript as well as standard JS.
I've been using statsd myself for a number of years and my current employer makes liberal use of it. Since the beginning of the attempted "revivial" of statsd I've picked up a number of PR reviews. I've also begun cleaning up the infrastructure and documentation.
Statsd is a very useful project and I'd like to see it continue to succeed and make aggregating metrics easy. I also like the challenge of bringing an older project up to date with current standards and practices.
cc @mrtazz

Add myself (elliot blackburn) to maintainers.md

---

lib/config.js
lib/helpers.js
lib/logger.js
lib/mgmt_console.js
lib/mgmt_server.js
lib/process_metrics.js
lib/process_mgmt.js
lib/set.js
run_tests.js
servers/tcp.js
servers/udp.js
stats.js

To begin bringing the codebase up to date with newer JS standards, this patch makes everything a `const` where possible and turns the rest into `let`'s. Thankfully nothing actually requires the flexible `var` scoping so we've been able to remove it completely.

Convert codebase from var -> let / const

---

.travis.yml
README.md

This PR tests statsd on all Current and LTS Node.js versions and declares their support in the readme. While `modern-syslog` isn't supported on any LTS or current versions of node  it isn't a blocker for install so I figured I'd propose this support scheme. It gives people ample time to upgrade and keeps the support burden much lower than trying to support nodejs versions without modern language features.

test and declare support for Current and LTS node

---

Changelog.md
debian/changelog

Extracted non-merge activity one-liners from git log and updated the changelogs to try and match the tagged releases to the changes.

Update Changelog.md and debian/changelog to reflect latest releases

---

debian/changelog
exampleConfig.js
lib/helpers.js
stats.js
test/graphite_delete_counters_tests.js

Hello here,
this PR is related to the following issue: https://github.com/etsy/statsd/issues/584
An overview of the changes I've made:
- Move away `idleStats` related configuration variables from the `flushMetrics` method
- Write new tests for the `gaugesMaxTTL` option
- Write the logic for handling the deletion in the presence of `gaugesMaxTTL`
The aim of this PR is to fix the behaviour involved in gauges deletion. 
The typical use case scenario is when gauges deletion is set to true via the `deleteGauges` flag but new values are actually sent with a frequency lower than the `flushInterval`.
In this case, the gauge's default behaviour and assumption of sending the previous value if no new one has been received since is broken by the gauge deletion process.
I've chosen the path of least …

Max ttl for gauges

---

Changelog.md
MAINTAINERS.md
README.md
docs/additional_tools.md
docs/admin_interface.md
docs/backend_interface.md
docs/client_implementations.md
docs/cluster_proxy.md
docs/graphite.md
docs/graphite_pickle.md
docs/metric_types.md
docs/server_implementations.md

Mostly, this makes the spelling of "StatsD" consistent. In addition, it fixes a few other typos.

Fix some typos in documentation

---

docs/backend.md

Elasticsearch 7 introduced major breaking changes by eliminating "Document Types" (deprecated in 6) which required some refactoring of the code to support the new bulk insert API data contracts.
Given that the current `statsd-elasticsearch-backend` hasn't received updates or accepted proposed pull requests to implement these changes, I've forked it and implemented the necessary changes for Elasticsearch 7 into a new package (`statsd-elasticsearch7-backend`).
This pull request simply updates the documentation to reflect this package distinction/separation.

Splitting doc links for Elasticsearch 7 backend

---

examples/StatsD.scala

Accepting the superclass ActorRefFactory allows passing either an ActorSystem (often more convenient) or an ActorContext for setup.

Change ActorContext to ActorRefFactory

---

backends/graphite.js
stats.js
test/graphite_tests.js

This PR adds full support for tagged metrics, including sensible handling for suffixes by adding them to the end of the metric name, before any tags.
It also adds support for the "dogstatsd" input format, and if dogstatsd-style tags are specified adds them as graphite tags.
This fixes the deficiencies noted in #696

Graphite tagged metrics support

---

docs/graphite.md
docs/metric_types.md
exampleConfig.js
examples/python_example.py
proxy.js

There are small typos in:
- docs/graphite.md
- docs/metric_types.md
- exampleConfig.js
- examples/python_example.py
- proxy.js
Fixes:
- Should read `occurrences` rather than `occurences`.
- Should read `undefined` rather than `undefinded`.
- Should read `signifying` rather than `signfying`.
- Should read `retrieves` rather than `retreives`.
- Should read `retrieved` rather than `retreived`.
- Should read `resources` rather than `recources`.
- Should read `metric` rather than `mertric`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

docker-compose.yml

The Docker Compose syntax has changed since this file was added. This makes the configuration actually work with modern docker-compose.

Fixed docker-compose configuration for 2

---

.travis.yml
Dockerfile
test/graphite_pickle_tests.js

Hi
I opened an issue here: https://github.com/statsd/statsd/issues/737. The official docker image is running a deprecated Debian version and deprecated Node version. 
I have run the tests locally under Node 18 and Node 16 and they all pass. 
Please let me know if there are further changes I should make.

Update Node base for the Docker image

---

.github/workflows/package-and-publish-image.yml

Below change will enable building and releasing multi-arch statsd images for amd64 and s390x.
More platforms can be enabled by appending those to "platforms" parameter below.
Is existing docker image not public on ghcr? It gives unauthorized error if pulled.

Create multi-arch images

---

.github/workflows/package-and-publish-image.yml

Hey!
It would be nice to add arm64 architecture. This architecture is often necessary for our tasks, could we add this in the build?
I checked the arm64 build on my fork, everything is builded correctly.
@elliotblackburn

Enable arm64 build
